// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// 初始化参数（对应 init 时设置，与 SDK 文档一致）
class InitOptions {
  InitOptions({
    required this.apiKey,
    this.coordinateType,
    this.mockEnable,
    this.requestLevel,
    this.locMode,
    this.allowGps,
    this.indoorLocationMode,
    this.gpsFirst,
    this.gpsFirstTimeOutMs,
  });

  String apiKey;

  /// 0=GCJ02, 1=WGS84
  int? coordinateType;

  bool? mockEnable;

  /// 0/1/3/4 对应 GEO/NAME/ADMIN_AREA/POI
  int? requestLevel;

  /// Android: 10/11/12；iOS 忽略
  int? locMode;

  bool? allowGps;

  bool? indoorLocationMode;

  /// 首次是否等待卫星定位结果
  bool? gpsFirst;

  /// 卫星定位优先时的超时时间 ms，最多 60000
  int? gpsFirstTimeOutMs;

  Object encode() {
    return <Object?>[
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    ];
  }

  static InitOptions decode(Object result) {
    result as List<Object?>;
    return InitOptions(
      apiKey: result[0]! as String,
      coordinateType: result[1] as int?,
      mockEnable: result[2] as bool?,
      requestLevel: result[3] as int?,
      locMode: result[4] as int?,
      allowGps: result[5] as bool?,
      indoorLocationMode: result[6] as bool?,
      gpsFirst: result[7] as bool?,
      gpsFirstTimeOutMs: result[8] as int?,
    );
  }
}

/// 连续定位请求参数（与 TencentLocationRequest 对应）
class ContinuousLocationRequest {
  ContinuousLocationRequest({
    required this.intervalMs,
    this.requestLevel,
    this.locMode,
    this.allowGps,
    this.allowCache,
    this.gpsFirst,
    this.gpsFirstTimeOutMs,
    this.backgroundLocation,
  });

  /// 定位周期/回调周期，单位 ms。>0 时按周期回调；0 仅在有新结果时回调。建议 5000–10000
  int intervalMs;

  /// 与 InitOptions 一致，不传则用 init 时的值
  int? requestLevel;

  int? locMode;

  bool? allowGps;

  bool? allowCache;

  bool? gpsFirst;

  int? gpsFirstTimeOutMs;

  /// 是否后台定位（Android 前台通知等）
  bool? backgroundLocation;

  Object encode() {
    return <Object?>[
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    ];
  }

  static ContinuousLocationRequest decode(Object result) {
    result as List<Object?>;
    return ContinuousLocationRequest(
      intervalMs: result[0]! as int,
      requestLevel: result[1] as int?,
      locMode: result[2] as int?,
      allowGps: result[3] as bool?,
      allowCache: result[4] as bool?,
      gpsFirst: result[5] as bool?,
      gpsFirstTimeOutMs: result[6] as int?,
      backgroundLocation: result[7] as bool?,
    );
  }
}

/// 连续定位过程中可更新的参数（仅传需要修改的字段）
/// Android: 间隔可通过 changeCallbackInterval 修改；其它需重新 requestLocationUpdates
/// iOS: 可动态改 locationCallbackInterval、requestLevel 等属性
class LocationRequestUpdate {
  LocationRequestUpdate({
    this.intervalMs,
    this.requestLevel,
    this.locMode,
    this.gpsFirstTimeOutMs,
    this.allowGps,
    this.allowCache,
    this.gpsFirst,
  });

  int? intervalMs;

  int? requestLevel;

  int? locMode;

  int? gpsFirstTimeOutMs;

  bool? allowGps;

  bool? allowCache;

  bool? gpsFirst;

  Object encode() {
    return <Object?>[
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    ];
  }

  static LocationRequestUpdate decode(Object result) {
    result as List<Object?>;
    return LocationRequestUpdate(
      intervalMs: result[0] as int?,
      requestLevel: result[1] as int?,
      locMode: result[2] as int?,
      gpsFirstTimeOutMs: result[3] as int?,
      allowGps: result[4] as bool?,
      allowCache: result[5] as bool?,
      gpsFirst: result[6] as bool?,
    );
  }
}

/// Android 前台定位通知配置
class AndroidNotificationOptions {
  AndroidNotificationOptions({
    required this.id,
    required this.channelId,
    required this.channelName,
    this.channelDescription,
    required this.notificationTitle,
    this.notificationText,
    this.enableVibration,
    this.playSound,
    this.showWhen,
    this.iconData,
  });

  int id;

  String channelId;

  String channelName;

  String? channelDescription;

  String notificationTitle;

  String? notificationText;

  bool? enableVibration;

  bool? playSound;

  bool? showWhen;

  NotificationIconData? iconData;

  Object encode() {
    return <Object?>[
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
      iconData,
    ];
  }

  static AndroidNotificationOptions decode(Object result) {
    result as List<Object?>;
    return AndroidNotificationOptions(
      id: result[0]! as int,
      channelId: result[1]! as String,
      channelName: result[2]! as String,
      channelDescription: result[3] as String?,
      notificationTitle: result[4]! as String,
      notificationText: result[5] as String?,
      enableVibration: result[6] as bool?,
      playSound: result[7] as bool?,
      showWhen: result[8] as bool?,
      iconData: result[9] as NotificationIconData?,
    );
  }
}

class NotificationIconData {
  NotificationIconData({
    this.bitmapPath,
    this.resourceId,
  });

  String? bitmapPath;

  int? resourceId;

  Object encode() {
    return <Object?>[
      bitmapPath,
      resourceId,
    ];
  }

  static NotificationIconData decode(Object result) {
    result as List<Object?>;
    return NotificationIconData(
      bitmapPath: result[0] as String?,
      resourceId: result[1] as int?,
    );
  }
}

/// 定位结果（与 TencentLocation / TencentLBSLocation 对应）
class LocationData {
  LocationData({
    this.code,
    this.latitude,
    this.longitude,
    this.altitude,
    this.accuracy,
    this.speed,
    this.bearing,
    this.address,
    this.name,
    this.timeIso,
    this.timeMs,
    this.sourceProvider,
  });

  int? code;

  double? latitude;

  double? longitude;

  double? altitude;

  double? accuracy;

  double? speed;

  double? bearing;

  String? address;

  String? name;

  String? timeIso;

  int? timeMs;

  String? sourceProvider;

  Object encode() {
    return <Object?>[
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
    ];
  }

  static LocationData decode(Object result) {
    result as List<Object?>;
    return LocationData(
      code: result[0] as int?,
      latitude: result[1] as double?,
      longitude: result[2] as double?,
      altitude: result[3] as double?,
      accuracy: result[4] as double?,
      speed: result[5] as double?,
      bearing: result[6] as double?,
      address: result[7] as String?,
      name: result[8] as String?,
      timeIso: result[9] as String?,
      timeMs: result[10] as int?,
      sourceProvider: result[11] as String?,
    );
  }
}

/// 状态回调（仅 Android onStatusUpdate）
class LocationStatusData {
  LocationStatusData({
    this.name,
    this.status,
  });

  String? name;

  int? status;

  Object encode() {
    return <Object?>[
      name,
      status,
    ];
  }

  static LocationStatusData decode(Object result) {
    result as List<Object?>;
    return LocationStatusData(
      name: result[0] as String?,
      status: result[1] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is InitOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ContinuousLocationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LocationRequestUpdate) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidNotificationOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NotificationIconData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is LocationData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is LocationStatusData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return InitOptions.decode(readValue(buffer)!);
      case 130: 
        return ContinuousLocationRequest.decode(readValue(buffer)!);
      case 131: 
        return LocationRequestUpdate.decode(readValue(buffer)!);
      case 132: 
        return AndroidNotificationOptions.decode(readValue(buffer)!);
      case 133: 
        return NotificationIconData.decode(readValue(buffer)!);
      case 134: 
        return LocationData.decode(readValue(buffer)!);
      case 135: 
        return LocationStatusData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TencentLBSHostApi {
  /// Constructor for [TencentLBSHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TencentLBSHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 对应 SDK 初始化（方法名避免 Swift 保留字 init）
  Future<bool> configure(InitOptions options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.configure$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> setUserAgreePrivacy(bool agree) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[agree]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> requestLocationOnce() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startLocationUpdates(ContinuousLocationRequest request, AndroidNotificationOptions? androidNotificationOptions) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request, androidNotificationOptions]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等）
  Future<void> updateLocationRequest(LocationRequestUpdate? update) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[update]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopLocationUpdates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class TencentLBSFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onLocation(LocationData location);

  void onError(int code, String message);

  void onStatus(LocationStatusData? status);

  static void setUp(TencentLBSFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LocationData? arg_location = (args[0] as LocationData?);
          assert(arg_location != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation was null, expected non-null LocationData.');
          try {
            api.onLocation(arg_location!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_code = (args[0] as int?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null, expected non-null int.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LocationStatusData? arg_status = (args[0] as LocationStatusData?);
          try {
            api.onStatus(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
