// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// 初始化参数。对应 Android TencentLocationManagerOptions + TencentLocationManager + TencentLocationRequest 的初始设置；iOS TencentLBSLocationManager 的 apiKey、coordinateType、requestLevel 等。
class InitOptions {
  InitOptions({
    required this.apiKey,
    this.coordinateType,
    this.mockEnable,
    this.requestLevel,
    this.locMode,
    this.allowGps,
    this.indoorLocationMode,
    this.gpsFirst,
    this.gpsFirstTimeOutMs,
  });

  /// 腾讯开放平台申请的 Key。Android: TencentLocationManagerOptions.setKey；iOS: apiKey。
  String apiKey;

  /// 坐标系类型。0=GCJ02（火星坐标，大陆返回 GCJ02 大陆外返回 WGS84）；1=WGS84（地球坐标，均返回 WGS84）。Android: TencentLocationManager.coordinateType；iOS: TencentLBSLocationCoordinateType。
  int? coordinateType;

  /// 是否允许 Mock 定位。Android: TencentLocationManager.setMockEnable。
  bool? mockEnable;

  /// 定位结果信息级别。不同 level 结果信息完整程度不同，信息越多消耗流量越多。Android: TencentLocationRequest.setRequestLevel。0=仅经纬度，1=经纬度+位置名称+地址，3=经纬度+行政区划+地址+名称，4=经纬度+行政区划+附近POI。
  int? requestLevel;

  /// 定位模式（仅 Android）。TencentLocationRequest.setLocMode。10=高精度(网络+卫星)，11=仅网络(不启GPS、省电、精度降低)，12=仅GPS(室外约3-10米，首次较慢耗电高，超时8s无GPS则返回网络)。iOS 无此参数，传参在 iOS 端忽略。
  int? locMode;

  /// 是否允许使用 GPS（仅 Android）。TencentLocationRequest.setAllowGPS，默认允许。允许时室外可提升精度约3-10米，首次较慢耗电较高。仅对高精度定位模式生效。
  bool? allowGps;

  /// 是否启动室内定位（仅 Android）。TencentLocationRequest.setIndoorLocationMode。
  bool? indoorLocationMode;

  /// 首次定位是否等待卫星定位结果（仅 Android）。TencentLocationRequest.setGpsFirst，默认 false。为 true 时首次定位会等待卫星结果，超时后返回网络定位结果。仅高精度模式生效。
  bool? gpsFirst;

  /// 卫星定位优先时，等待卫星定位结果的超时时间（仅 Android）。TencentLocationRequest.setGpsFirstTimeOut，单位 ms，最多 60s。
  int? gpsFirstTimeOutMs;

  Object encode() {
    return <Object?>[
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    ];
  }

  static InitOptions decode(Object result) {
    result as List<Object?>;
    return InitOptions(
      apiKey: result[0]! as String,
      coordinateType: result[1] as int?,
      mockEnable: result[2] as bool?,
      requestLevel: result[3] as int?,
      locMode: result[4] as int?,
      allowGps: result[5] as bool?,
      indoorLocationMode: result[6] as bool?,
      gpsFirst: result[7] as bool?,
      gpsFirstTimeOutMs: result[8] as int?,
    );
  }
}

/// 连续定位请求参数。对应 Android TencentLocationRequest；iOS 连续定位时的 interval、requestLevel 等。
class ContinuousLocationRequest {
  ContinuousLocationRequest({
    required this.intervalMs,
    this.requestLevel,
    this.locMode,
    this.allowGps,
    this.allowCache,
    this.gpsFirst,
    this.gpsFirstTimeOutMs,
    this.backgroundLocation,
  });

  /// 定位周期（位置监听器回调周期），单位 ms。Android: TencentLocationRequest.setInterval。大于 0 时按周期定时回调；等于 0 时仅当有新的定位结果时回调。文档建议 5000-10000ms，不建议 1000ms 以下，且不得小于 1000ms。
  int intervalMs;

  /// 定位结果信息级别，同 InitOptions.requestLevel。不传则使用 init 时的值。
  int? requestLevel;

  /// 定位模式（仅 Android），同 InitOptions.locMode。
  int? locMode;

  /// 是否允许使用 GPS（仅 Android），同 InitOptions.allowGps。
  bool? allowGps;

  /// 是否允许使用缓存（仅 Android）。TencentLocationRequest.setAllowCache。允许时用户移动范围较小时可减少网络请求、节省电量和流量；长时间连续定位建议允许，单次定位建议不使用。
  bool? allowCache;

  /// 首次是否等待卫星结果（仅 Android），同 InitOptions.gpsFirst。
  bool? gpsFirst;

  /// 卫星优先超时时间 ms（仅 Android），同 InitOptions.gpsFirstTimeOutMs。
  int? gpsFirstTimeOutMs;

  /// 是否后台定位。为 true 时 Android 需配合前台通知（enableForegroundLocation）；iOS 需配置后台定位能力。
  bool? backgroundLocation;

  Object encode() {
    return <Object?>[
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    ];
  }

  static ContinuousLocationRequest decode(Object result) {
    result as List<Object?>;
    return ContinuousLocationRequest(
      intervalMs: result[0]! as int,
      requestLevel: result[1] as int?,
      locMode: result[2] as int?,
      allowGps: result[3] as bool?,
      allowCache: result[4] as bool?,
      gpsFirst: result[5] as bool?,
      gpsFirstTimeOutMs: result[6] as int?,
      backgroundLocation: result[7] as bool?,
    );
  }
}

/// 连续定位过程中可更新的参数，仅传需要修改的字段。Android：间隔可通过 changeCallbackInterval 修改，其它需重新 requestLocationUpdates；iOS：可动态修改 locationCallbackInterval、requestLevel 等。
class LocationRequestUpdate {
  LocationRequestUpdate({
    this.intervalMs,
    this.requestLevel,
    this.locMode,
    this.gpsFirstTimeOutMs,
    this.allowGps,
    this.allowCache,
    this.gpsFirst,
  });

  int? intervalMs;

  int? requestLevel;

  int? locMode;

  int? gpsFirstTimeOutMs;

  bool? allowGps;

  bool? allowCache;

  bool? gpsFirst;

  Object encode() {
    return <Object?>[
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    ];
  }

  static LocationRequestUpdate decode(Object result) {
    result as List<Object?>;
    return LocationRequestUpdate(
      intervalMs: result[0] as int?,
      requestLevel: result[1] as int?,
      locMode: result[2] as int?,
      gpsFirstTimeOutMs: result[3] as int?,
      allowGps: result[4] as bool?,
      allowCache: result[5] as bool?,
      gpsFirst: result[6] as bool?,
    );
  }
}

/// Android 后台定位时的前台通知配置。Android 后台定位需前台服务并显示通知，通过 TencentLocationManager.enableForegroundLocation(notifId, notification) 绑定；id 为通知 ID，channelId/channelName 为通知渠道，notificationTitle/notificationText 为通知标题与内容。
class AndroidNotificationOptions {
  AndroidNotificationOptions({
    required this.id,
    required this.channelId,
    required this.channelName,
    this.channelDescription,
    required this.notificationTitle,
    this.notificationText,
    this.enableVibration,
    this.playSound,
    this.showWhen,
  });

  /// 前台定位通知 ID，用于 enableForegroundLocation(id, notification)。
  int id;

  /// 通知渠道 ID（Android NotificationChannel）。
  String channelId;

  /// 通知渠道名称。
  String channelName;

  /// 通知渠道描述（可选）。
  String? channelDescription;

  /// 通知标题。
  String notificationTitle;

  /// 通知内容（可选）。
  String? notificationText;

  /// 是否振动。
  bool? enableVibration;

  /// 是否播放声音。
  bool? playSound;

  /// 是否显示时间。
  bool? showWhen;

  Object encode() {
    return <Object?>[
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
    ];
  }

  static AndroidNotificationOptions decode(Object result) {
    result as List<Object?>;
    return AndroidNotificationOptions(
      id: result[0]! as int,
      channelId: result[1]! as String,
      channelName: result[2]! as String,
      channelDescription: result[3] as String?,
      notificationTitle: result[4]! as String,
      notificationText: result[5] as String?,
      enableVibration: result[6] as bool?,
      playSound: result[7] as bool?,
      showWhen: result[8] as bool?,
    );
  }
}

/// 定位结果。对应 Android TencentLocation 接口、iOS TencentLBSLocation 返回字段。
class LocationData {
  LocationData({
    this.code,
    this.latitude,
    this.longitude,
    this.altitude,
    this.accuracy,
    this.horizontalAccuracy,
    this.verticalAccuracy,
    this.speed,
    this.bearing,
    this.address,
    this.name,
    this.timeIso,
    this.timeMs,
    this.sourceProvider,
    this.locationSource,
  });

  /// 错误码。Android TencentLocation：0=ERROR_OK 定位成功，1=ERROR_NETWORK 网络问题，2=ERROR_BAD_JSON GPS/WiFi/基站错误，4=ERROR_WGS84 无法进行坐标转换，404=ERROR_UNKNOWN 未知原因。
  int? code;

  /// 纬度。TencentLocation.getLatitude。
  double? latitude;

  /// 经度。TencentLocation.getLongitude。
  double? longitude;

  /// 海拔，单位 m。TencentLocation.getAltitude，仅当位置来自 GPS 时可能有效。
  double? altitude;

  /// 精度，单位 m（水平精度）。TencentLocation.getAccuracy / CLLocation.horizontalAccuracy。
  double? accuracy;

  /// 水平精度，单位 m。与 accuracy 同源，语义明确。
  double? horizontalAccuracy;

  /// 垂直精度（海拔精度），单位 m。仅 iOS CLLocation.verticalAccuracy 有值，Android 为 null。
  double? verticalAccuracy;

  /// 移动速度，单位 m/s。TencentLocation.getSpeed，仅当位置来自 GPS 时可能有效。
  double? speed;

  /// 方向/朝向，单位度（0～360）。TencentLocation.getBearing / CLLocation.course，仅当位置来自 GPS 时可能有效。
  double? bearing;

  /// 位置地址。TencentLocation.getAddress，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。
  String? address;

  /// 位置名称。TencentLocation.getName，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。
  String? name;

  /// 时间 ISO 字符串（可选，非 SDK 必返字段）。
  String? timeIso;

  /// 当前位置生成时间，毫秒时间戳。TencentLocation.getTime。
  int? timeMs;

  /// 位置细分来源（原生原始值）。Android: TencentLocation.getSourceProvider()；iOS 可为 null，以 locationSource 为准。
  String? sourceProvider;

  /// 定位来源（双端统一）。-1=未知，0=GPS，1=网络，2=模拟，3=外设GPS，4=外设网络。见 LocationSource。
  int? locationSource;

  Object encode() {
    return <Object?>[
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      horizontalAccuracy,
      verticalAccuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
      locationSource,
    ];
  }

  static LocationData decode(Object result) {
    result as List<Object?>;
    return LocationData(
      code: result[0] as int?,
      latitude: result[1] as double?,
      longitude: result[2] as double?,
      altitude: result[3] as double?,
      accuracy: result[4] as double?,
      horizontalAccuracy: result[5] as double?,
      verticalAccuracy: result[6] as double?,
      speed: result[7] as double?,
      bearing: result[8] as double?,
      address: result[9] as String?,
      name: result[10] as String?,
      timeIso: result[11] as String?,
      timeMs: result[12] as int?,
      sourceProvider: result[13] as String?,
      locationSource: result[14] as int?,
    );
  }
}

/// 状态回调数据（仅 Android）。对应 TencentLocationListener.onStatusUpdate(name, status, desc)。使用 status 前请先按 name 区分设备。name 为设备名如 "GPS"、"WIFI"、"CELL"；status 为状态码，参见 SDK 状态码对照表。
class LocationStatusData {
  LocationStatusData({
    this.name,
    this.status,
  });

  String? name;

  int? status;

  Object encode() {
    return <Object?>[
      name,
      status,
    ];
  }

  static LocationStatusData decode(Object result) {
    result as List<Object?>;
    return LocationStatusData(
      name: result[0] as String?,
      status: result[1] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is InitOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ContinuousLocationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LocationRequestUpdate) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidNotificationOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is LocationData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is LocationStatusData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return InitOptions.decode(readValue(buffer)!);
      case 130: 
        return ContinuousLocationRequest.decode(readValue(buffer)!);
      case 131: 
        return LocationRequestUpdate.decode(readValue(buffer)!);
      case 132: 
        return AndroidNotificationOptions.decode(readValue(buffer)!);
      case 133: 
        return LocationData.decode(readValue(buffer)!);
      case 134: 
        return LocationStatusData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TencentLBSHostApi {
  /// Constructor for [TencentLBSHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TencentLBSHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// SDK 初始化（方法名避免 Swift 保留字 init）。Android: TencentLocationManagerOptions.setKey + TencentLocationManager 实例及 Request 配置；iOS: TencentLBSLocationManager 配置。
  Future<bool> configure(InitOptions options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.configure$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// 设置用户是否同意隐私政策，调用其他接口前必须调用。对应 SDK setUserAgreePrivacy。
  Future<void> setUserAgreePrivacy(bool agree) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[agree]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 单次定位。Android: requestSingleFreshLocation；iOS: requestLocation。
  Future<void> requestLocationOnce() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 发起连续定位。Android: requestLocationUpdates；iOS: startUpdatingLocation。androidNotificationOptions 仅 Android 后台定位时用于构建前台通知。
  Future<void> startLocationUpdates(ContinuousLocationRequest request, AndroidNotificationOptions? androidNotificationOptions) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request, androidNotificationOptions]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 连续定位开启后可调用，更新部分参数（如定位间隔、requestLevel 等）。Android 间隔可通过 changeCallbackInterval 修改。
  Future<void> updateLocationRequest(LocationRequestUpdate? update) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[update]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 停止连续定位。Android: removeUpdates；iOS: stopUpdatingLocation。
  Future<void> stopLocationUpdates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class TencentLBSFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onLocation(LocationData location);

  void onError(int code, String message);

  void onStatus(LocationStatusData? status);

  static void setUp(TencentLBSFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LocationData? arg_location = (args[0] as LocationData?);
          assert(arg_location != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation was null, expected non-null LocationData.');
          try {
            api.onLocation(arg_location!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_code = (args[0] as int?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null, expected non-null int.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LocationStatusData? arg_status = (args[0] as LocationStatusData?);
          try {
            api.onStatus(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
