// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flutter_tencent_lbs_plugin.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 初始化参数。对应 Android TencentLocationManagerOptions + TencentLocationManager + TencentLocationRequest 的初始设置；iOS TencentLBSLocationManager 的 apiKey、coordinateType、requestLevel 等。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitOptions (
  /** 腾讯开放平台申请的 Key。Android: TencentLocationManagerOptions.setKey；iOS: apiKey。 */
  val apiKey: String,
  /** 坐标系类型。0=GCJ02（火星坐标，大陆返回 GCJ02 大陆外返回 WGS84）；1=WGS84（地球坐标，均返回 WGS84）。Android: TencentLocationManager.coordinateType；iOS: TencentLBSLocationCoordinateType。 */
  val coordinateType: Long? = null,
  /** 是否允许 Mock 定位。Android: TencentLocationManager.setMockEnable。 */
  val mockEnable: Boolean? = null,
  /** 定位结果信息级别。不同 level 结果信息完整程度不同，信息越多消耗流量越多。Android: TencentLocationRequest.setRequestLevel。0=仅经纬度，1=经纬度+位置名称+地址，3=经纬度+行政区划+地址+名称，4=经纬度+行政区划+附近POI。 */
  val requestLevel: Long? = null,
  /** 定位模式（仅 Android）。TencentLocationRequest.setLocMode。10=高精度(网络+卫星)，11=仅网络(不启GPS、省电、精度降低)，12=仅GPS(室外约3-10米，首次较慢耗电高，超时8s无GPS则返回网络)。iOS 无此参数，传参在 iOS 端忽略。 */
  val locMode: Long? = null,
  /** 是否允许使用 GPS（仅 Android）。TencentLocationRequest.setAllowGPS，默认允许。允许时室外可提升精度约3-10米，首次较慢耗电较高。仅对高精度定位模式生效。 */
  val allowGps: Boolean? = null,
  /** 是否启动室内定位（仅 Android）。TencentLocationRequest.setIndoorLocationMode。 */
  val indoorLocationMode: Boolean? = null,
  /** 首次定位是否等待卫星定位结果（仅 Android）。TencentLocationRequest.setGpsFirst，默认 false。为 true 时首次定位会等待卫星结果，超时后返回网络定位结果。仅高精度模式生效。 */
  val gpsFirst: Boolean? = null,
  /** 卫星定位优先时，等待卫星定位结果的超时时间（仅 Android）。TencentLocationRequest.setGpsFirstTimeOut，单位 ms，最多 60s。 */
  val gpsFirstTimeOutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitOptions {
      val apiKey = pigeonVar_list[0] as String
      val coordinateType = pigeonVar_list[1] as Long?
      val mockEnable = pigeonVar_list[2] as Boolean?
      val requestLevel = pigeonVar_list[3] as Long?
      val locMode = pigeonVar_list[4] as Long?
      val allowGps = pigeonVar_list[5] as Boolean?
      val indoorLocationMode = pigeonVar_list[6] as Boolean?
      val gpsFirst = pigeonVar_list[7] as Boolean?
      val gpsFirstTimeOutMs = pigeonVar_list[8] as Long?
      return InitOptions(apiKey, coordinateType, mockEnable, requestLevel, locMode, allowGps, indoorLocationMode, gpsFirst, gpsFirstTimeOutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    )
  }
}

/**
 * 连续定位请求参数。对应 Android TencentLocationRequest；iOS 连续定位时的 interval、requestLevel 等。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ContinuousLocationRequest (
  /** 定位周期（位置监听器回调周期），单位 ms。Android: TencentLocationRequest.setInterval。大于 0 时按周期定时回调；等于 0 时仅当有新的定位结果时回调。文档建议 5000-10000ms，不建议 1000ms 以下，且不得小于 1000ms。 */
  val intervalMs: Long,
  /** 定位结果信息级别，同 InitOptions.requestLevel。不传则使用 init 时的值。 */
  val requestLevel: Long? = null,
  /** 定位模式（仅 Android），同 InitOptions.locMode。 */
  val locMode: Long? = null,
  /** 是否允许使用 GPS（仅 Android），同 InitOptions.allowGps。 */
  val allowGps: Boolean? = null,
  /** 是否允许使用缓存（仅 Android）。TencentLocationRequest.setAllowCache。允许时用户移动范围较小时可减少网络请求、节省电量和流量；长时间连续定位建议允许，单次定位建议不使用。 */
  val allowCache: Boolean? = null,
  /** 首次是否等待卫星结果（仅 Android），同 InitOptions.gpsFirst。 */
  val gpsFirst: Boolean? = null,
  /** 卫星优先超时时间 ms（仅 Android），同 InitOptions.gpsFirstTimeOutMs。 */
  val gpsFirstTimeOutMs: Long? = null,
  /** 是否后台定位。为 true 时 Android 需配合前台通知（enableForegroundLocation）；iOS 需配置后台定位能力。 */
  val backgroundLocation: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContinuousLocationRequest {
      val intervalMs = pigeonVar_list[0] as Long
      val requestLevel = pigeonVar_list[1] as Long?
      val locMode = pigeonVar_list[2] as Long?
      val allowGps = pigeonVar_list[3] as Boolean?
      val allowCache = pigeonVar_list[4] as Boolean?
      val gpsFirst = pigeonVar_list[5] as Boolean?
      val gpsFirstTimeOutMs = pigeonVar_list[6] as Long?
      val backgroundLocation = pigeonVar_list[7] as Boolean?
      return ContinuousLocationRequest(intervalMs, requestLevel, locMode, allowGps, allowCache, gpsFirst, gpsFirstTimeOutMs, backgroundLocation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    )
  }
}

/**
 * 连续定位过程中可更新的参数，仅传需要修改的字段。Android：间隔可通过 changeCallbackInterval 修改，其它需重新 requestLocationUpdates；iOS：可动态修改 locationCallbackInterval、requestLevel 等。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationRequestUpdate (
  val intervalMs: Long? = null,
  val requestLevel: Long? = null,
  val locMode: Long? = null,
  val gpsFirstTimeOutMs: Long? = null,
  val allowGps: Boolean? = null,
  val allowCache: Boolean? = null,
  val gpsFirst: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationRequestUpdate {
      val intervalMs = pigeonVar_list[0] as Long?
      val requestLevel = pigeonVar_list[1] as Long?
      val locMode = pigeonVar_list[2] as Long?
      val gpsFirstTimeOutMs = pigeonVar_list[3] as Long?
      val allowGps = pigeonVar_list[4] as Boolean?
      val allowCache = pigeonVar_list[5] as Boolean?
      val gpsFirst = pigeonVar_list[6] as Boolean?
      return LocationRequestUpdate(intervalMs, requestLevel, locMode, gpsFirstTimeOutMs, allowGps, allowCache, gpsFirst)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    )
  }
}

/**
 * Android 后台定位时的前台通知配置。Android 后台定位需前台服务并显示通知，通过 TencentLocationManager.enableForegroundLocation(notifId, notification) 绑定；id 为通知 ID，channelId/channelName 为通知渠道，notificationTitle/notificationText 为通知标题与内容。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidNotificationOptions (
  /** 前台定位通知 ID，用于 enableForegroundLocation(id, notification)。 */
  val id: Long,
  /** 通知渠道 ID（Android NotificationChannel）。 */
  val channelId: String,
  /** 通知渠道名称。 */
  val channelName: String,
  /** 通知渠道描述（可选）。 */
  val channelDescription: String? = null,
  /** 通知标题。 */
  val notificationTitle: String,
  /** 通知内容（可选）。 */
  val notificationText: String? = null,
  /** 是否振动。 */
  val enableVibration: Boolean? = null,
  /** 是否播放声音。 */
  val playSound: Boolean? = null,
  /** 是否显示时间。 */
  val showWhen: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidNotificationOptions {
      val id = pigeonVar_list[0] as Long
      val channelId = pigeonVar_list[1] as String
      val channelName = pigeonVar_list[2] as String
      val channelDescription = pigeonVar_list[3] as String?
      val notificationTitle = pigeonVar_list[4] as String
      val notificationText = pigeonVar_list[5] as String?
      val enableVibration = pigeonVar_list[6] as Boolean?
      val playSound = pigeonVar_list[7] as Boolean?
      val showWhen = pigeonVar_list[8] as Boolean?
      return AndroidNotificationOptions(id, channelId, channelName, channelDescription, notificationTitle, notificationText, enableVibration, playSound, showWhen)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
    )
  }
}

/**
 * 定位结果。对应 Android TencentLocation 接口、iOS TencentLBSLocation 返回字段。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationData (
  /** 错误码。Android TencentLocation：0=ERROR_OK 定位成功，1=ERROR_NETWORK 网络问题，2=ERROR_BAD_JSON GPS/WiFi/基站错误，4=ERROR_WGS84 无法进行坐标转换，404=ERROR_UNKNOWN 未知原因。 */
  val code: Long? = null,
  /** 纬度。TencentLocation.getLatitude。 */
  val latitude: Double? = null,
  /** 经度。TencentLocation.getLongitude。 */
  val longitude: Double? = null,
  /** 海拔，单位 m。TencentLocation.getAltitude，仅当位置来自 GPS 时可能有效。 */
  val altitude: Double? = null,
  /** 精度，单位 m（水平精度）。TencentLocation.getAccuracy / CLLocation.horizontalAccuracy。 */
  val accuracy: Double? = null,
  /** 水平精度，单位 m。与 accuracy 同源，语义明确。 */
  val horizontalAccuracy: Double? = null,
  /** 垂直精度（海拔精度），单位 m。仅 iOS CLLocation.verticalAccuracy 有值，Android 为 null。 */
  val verticalAccuracy: Double? = null,
  /** 移动速度，单位 m/s。TencentLocation.getSpeed，仅当位置来自 GPS 时可能有效。 */
  val speed: Double? = null,
  /** 方向/朝向，单位度（0～360）。TencentLocation.getBearing / CLLocation.course，仅当位置来自 GPS 时可能有效。 */
  val bearing: Double? = null,
  /** 位置地址。TencentLocation.getAddress，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。 */
  val address: String? = null,
  /** 位置名称。TencentLocation.getName，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。 */
  val name: String? = null,
  /** 时间 ISO 字符串（可选，非 SDK 必返字段）。 */
  val timeIso: String? = null,
  /** 当前位置生成时间，毫秒时间戳。TencentLocation.getTime。 */
  val timeMs: Long? = null,
  /** 位置细分来源（原生原始值）。Android: TencentLocation.getSourceProvider()；iOS 可为 null，以 locationSource 为准。 */
  val sourceProvider: String? = null,
  /** 定位来源（双端统一）。-1=未知，0=GPS，1=网络，2=模拟，3=外设GPS，4=外设网络。见 LocationSource。 */
  val locationSource: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationData {
      val code = pigeonVar_list[0] as Long?
      val latitude = pigeonVar_list[1] as Double?
      val longitude = pigeonVar_list[2] as Double?
      val altitude = pigeonVar_list[3] as Double?
      val accuracy = pigeonVar_list[4] as Double?
      val horizontalAccuracy = pigeonVar_list[5] as Double?
      val verticalAccuracy = pigeonVar_list[6] as Double?
      val speed = pigeonVar_list[7] as Double?
      val bearing = pigeonVar_list[8] as Double?
      val address = pigeonVar_list[9] as String?
      val name = pigeonVar_list[10] as String?
      val timeIso = pigeonVar_list[11] as String?
      val timeMs = pigeonVar_list[12] as Long?
      val sourceProvider = pigeonVar_list[13] as String?
      val locationSource = pigeonVar_list[14] as Long?
      return LocationData(code, latitude, longitude, altitude, accuracy, horizontalAccuracy, verticalAccuracy, speed, bearing, address, name, timeIso, timeMs, sourceProvider, locationSource)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      horizontalAccuracy,
      verticalAccuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
      locationSource,
    )
  }
}

/**
 * 状态回调数据（仅 Android）。对应 TencentLocationListener.onStatusUpdate(name, status, desc)。使用 status 前请先按 name 区分设备。name 为设备名如 "GPS"、"WIFI"、"CELL"；status 为状态码，参见 SDK 状态码对照表。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationStatusData (
  val name: String? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationStatusData {
      val name = pigeonVar_list[0] as String?
      val status = pigeonVar_list[1] as Long?
      return LocationStatusData(name, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      status,
    )
  }
}
private open class LocationPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContinuousLocationRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationRequestUpdate.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidNotificationOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationStatusData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ContinuousLocationRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LocationRequestUpdate -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AndroidNotificationOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LocationData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LocationStatusData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TencentLBSHostApi {
  /** SDK 初始化（方法名避免 Swift 保留字 init）。Android: TencentLocationManagerOptions.setKey + TencentLocationManager 实例及 Request 配置；iOS: TencentLBSLocationManager 配置。 */
  fun configure(options: InitOptions): Boolean
  /** 设置用户是否同意隐私政策，调用其他接口前必须调用。对应 SDK setUserAgreePrivacy。 */
  fun setUserAgreePrivacy(agree: Boolean)
  /** 单次定位。Android: requestSingleFreshLocation；iOS: requestLocation。 */
  fun requestLocationOnce()
  /** 发起连续定位。Android: requestLocationUpdates；iOS: startUpdatingLocation。androidNotificationOptions 仅 Android 后台定位时用于构建前台通知。 */
  fun startLocationUpdates(request: ContinuousLocationRequest, androidNotificationOptions: AndroidNotificationOptions?)
  /** 连续定位开启后可调用，更新部分参数（如定位间隔、requestLevel 等）。Android 间隔可通过 changeCallbackInterval 修改。 */
  fun updateLocationRequest(update: LocationRequestUpdate?)
  /** 停止连续定位。Android: removeUpdates；iOS: stopUpdatingLocation。 */
  fun stopLocationUpdates()

  companion object {
    /** The codec used by TencentLBSHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationPigeonPigeonCodec()
    }
    /** Sets up an instance of `TencentLBSHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TencentLBSHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as InitOptions
            val wrapped: List<Any?> = try {
              listOf(api.configure(optionsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val agreeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setUserAgreePrivacy(agreeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestLocationOnce()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ContinuousLocationRequest
            val androidNotificationOptionsArg = args[1] as AndroidNotificationOptions?
            val wrapped: List<Any?> = try {
              api.startLocationUpdates(requestArg, androidNotificationOptionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val updateArg = args[0] as LocationRequestUpdate?
            val wrapped: List<Any?> = try {
              api.updateLocationRequest(updateArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopLocationUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TencentLBSFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TencentLBSFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationPigeonPigeonCodec()
    }
  }
  fun onLocation(locationArg: LocationData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(locationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: Long, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onStatus(statusArg: LocationStatusData?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
