// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flutter_tencent_lbs_plugin.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 初始化参数（对应 init 时设置，与 SDK 文档一致）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitOptions (
  val apiKey: String,
  /** 0=GCJ02, 1=WGS84 */
  val coordinateType: Long? = null,
  val mockEnable: Boolean? = null,
  /** 0/1/3/4 对应 GEO/NAME/ADMIN_AREA/POI */
  val requestLevel: Long? = null,
  /** Android: 10/11/12；iOS 忽略 */
  val locMode: Long? = null,
  val allowGps: Boolean? = null,
  val indoorLocationMode: Boolean? = null,
  /** 首次是否等待卫星定位结果 */
  val gpsFirst: Boolean? = null,
  /** 卫星定位优先时的超时时间 ms，最多 60000 */
  val gpsFirstTimeOutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitOptions {
      val apiKey = pigeonVar_list[0] as String
      val coordinateType = pigeonVar_list[1] as Long?
      val mockEnable = pigeonVar_list[2] as Boolean?
      val requestLevel = pigeonVar_list[3] as Long?
      val locMode = pigeonVar_list[4] as Long?
      val allowGps = pigeonVar_list[5] as Boolean?
      val indoorLocationMode = pigeonVar_list[6] as Boolean?
      val gpsFirst = pigeonVar_list[7] as Boolean?
      val gpsFirstTimeOutMs = pigeonVar_list[8] as Long?
      return InitOptions(apiKey, coordinateType, mockEnable, requestLevel, locMode, allowGps, indoorLocationMode, gpsFirst, gpsFirstTimeOutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    )
  }
}

/**
 * 连续定位请求参数（与 TencentLocationRequest 对应）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ContinuousLocationRequest (
  /** 定位周期/回调周期，单位 ms。>0 时按周期回调；0 仅在有新结果时回调。建议 5000–10000 */
  val intervalMs: Long,
  /** 与 InitOptions 一致，不传则用 init 时的值 */
  val requestLevel: Long? = null,
  val locMode: Long? = null,
  val allowGps: Boolean? = null,
  val allowCache: Boolean? = null,
  val gpsFirst: Boolean? = null,
  val gpsFirstTimeOutMs: Long? = null,
  /** 是否后台定位（Android 前台通知等） */
  val backgroundLocation: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContinuousLocationRequest {
      val intervalMs = pigeonVar_list[0] as Long
      val requestLevel = pigeonVar_list[1] as Long?
      val locMode = pigeonVar_list[2] as Long?
      val allowGps = pigeonVar_list[3] as Boolean?
      val allowCache = pigeonVar_list[4] as Boolean?
      val gpsFirst = pigeonVar_list[5] as Boolean?
      val gpsFirstTimeOutMs = pigeonVar_list[6] as Long?
      val backgroundLocation = pigeonVar_list[7] as Boolean?
      return ContinuousLocationRequest(intervalMs, requestLevel, locMode, allowGps, allowCache, gpsFirst, gpsFirstTimeOutMs, backgroundLocation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    )
  }
}

/**
 * 连续定位过程中可更新的参数（仅传需要修改的字段）
 * Android: 间隔可通过 changeCallbackInterval 修改；其它需重新 requestLocationUpdates
 * iOS: 可动态改 locationCallbackInterval、requestLevel 等属性
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationRequestUpdate (
  val intervalMs: Long? = null,
  val requestLevel: Long? = null,
  val locMode: Long? = null,
  val gpsFirstTimeOutMs: Long? = null,
  val allowGps: Boolean? = null,
  val allowCache: Boolean? = null,
  val gpsFirst: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationRequestUpdate {
      val intervalMs = pigeonVar_list[0] as Long?
      val requestLevel = pigeonVar_list[1] as Long?
      val locMode = pigeonVar_list[2] as Long?
      val gpsFirstTimeOutMs = pigeonVar_list[3] as Long?
      val allowGps = pigeonVar_list[4] as Boolean?
      val allowCache = pigeonVar_list[5] as Boolean?
      val gpsFirst = pigeonVar_list[6] as Boolean?
      return LocationRequestUpdate(intervalMs, requestLevel, locMode, gpsFirstTimeOutMs, allowGps, allowCache, gpsFirst)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    )
  }
}

/**
 * Android 前台定位通知配置
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidNotificationOptions (
  val id: Long,
  val channelId: String,
  val channelName: String,
  val channelDescription: String? = null,
  val notificationTitle: String,
  val notificationText: String? = null,
  val enableVibration: Boolean? = null,
  val playSound: Boolean? = null,
  val showWhen: Boolean? = null,
  val iconData: NotificationIconData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidNotificationOptions {
      val id = pigeonVar_list[0] as Long
      val channelId = pigeonVar_list[1] as String
      val channelName = pigeonVar_list[2] as String
      val channelDescription = pigeonVar_list[3] as String?
      val notificationTitle = pigeonVar_list[4] as String
      val notificationText = pigeonVar_list[5] as String?
      val enableVibration = pigeonVar_list[6] as Boolean?
      val playSound = pigeonVar_list[7] as Boolean?
      val showWhen = pigeonVar_list[8] as Boolean?
      val iconData = pigeonVar_list[9] as NotificationIconData?
      return AndroidNotificationOptions(id, channelId, channelName, channelDescription, notificationTitle, notificationText, enableVibration, playSound, showWhen, iconData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
      iconData,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationIconData (
  val bitmapPath: String? = null,
  val resourceId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationIconData {
      val bitmapPath = pigeonVar_list[0] as String?
      val resourceId = pigeonVar_list[1] as Long?
      return NotificationIconData(bitmapPath, resourceId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bitmapPath,
      resourceId,
    )
  }
}

/**
 * 定位结果（与 TencentLocation / TencentLBSLocation 对应）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationData (
  val code: Long? = null,
  val latitude: Double? = null,
  val longitude: Double? = null,
  val altitude: Double? = null,
  val accuracy: Double? = null,
  val speed: Double? = null,
  val bearing: Double? = null,
  val address: String? = null,
  val name: String? = null,
  val timeIso: String? = null,
  val timeMs: Long? = null,
  val sourceProvider: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationData {
      val code = pigeonVar_list[0] as Long?
      val latitude = pigeonVar_list[1] as Double?
      val longitude = pigeonVar_list[2] as Double?
      val altitude = pigeonVar_list[3] as Double?
      val accuracy = pigeonVar_list[4] as Double?
      val speed = pigeonVar_list[5] as Double?
      val bearing = pigeonVar_list[6] as Double?
      val address = pigeonVar_list[7] as String?
      val name = pigeonVar_list[8] as String?
      val timeIso = pigeonVar_list[9] as String?
      val timeMs = pigeonVar_list[10] as Long?
      val sourceProvider = pigeonVar_list[11] as String?
      return LocationData(code, latitude, longitude, altitude, accuracy, speed, bearing, address, name, timeIso, timeMs, sourceProvider)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
    )
  }
}

/**
 * 状态回调（仅 Android onStatusUpdate）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocationStatusData (
  val name: String? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationStatusData {
      val name = pigeonVar_list[0] as String?
      val status = pigeonVar_list[1] as Long?
      return LocationStatusData(name, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      status,
    )
  }
}
private open class LocationPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContinuousLocationRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationRequestUpdate.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidNotificationOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationIconData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationData.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationStatusData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ContinuousLocationRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LocationRequestUpdate -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AndroidNotificationOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NotificationIconData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LocationData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is LocationStatusData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TencentLBSHostApi {
  fun init(options: InitOptions): Boolean
  fun setUserAgreePrivacy(agree: Boolean)
  fun requestLocationOnce()
  fun startLocationUpdates(request: ContinuousLocationRequest, androidNotificationOptions: AndroidNotificationOptions?)
  /** 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等） */
  fun updateLocationRequest(update: LocationRequestUpdate?)
  fun stopLocationUpdates()

  companion object {
    /** The codec used by TencentLBSHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationPigeonPigeonCodec()
    }
    /** Sets up an instance of `TencentLBSHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TencentLBSHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.init$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as InitOptions
            val wrapped: List<Any?> = try {
              listOf(api.init(optionsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val agreeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setUserAgreePrivacy(agreeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestLocationOnce()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ContinuousLocationRequest
            val androidNotificationOptionsArg = args[1] as AndroidNotificationOptions?
            val wrapped: List<Any?> = try {
              api.startLocationUpdates(requestArg, androidNotificationOptionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val updateArg = args[0] as LocationRequestUpdate?
            val wrapped: List<Any?> = try {
              api.updateLocationRequest(updateArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopLocationUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TencentLBSFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TencentLBSFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationPigeonPigeonCodec()
    }
  }
  fun onLocation(locationArg: LocationData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(locationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: Long, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onStatus(statusArg: LocationStatusData?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
