// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTInitOptions;
@class FLTContinuousLocationRequest;
@class FLTLocationRequestUpdate;
@class FLTAndroidNotificationOptions;
@class FLTNotificationIconData;
@class FLTLocationData;
@class FLTLocationStatusData;

/// 初始化参数（对应 init 时设置，与 SDK 文档一致）
@interface FLTInitOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    coordinateType:(nullable NSNumber *)coordinateType
    mockEnable:(nullable NSNumber *)mockEnable
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    allowGps:(nullable NSNumber *)allowGps
    indoorLocationMode:(nullable NSNumber *)indoorLocationMode
    gpsFirst:(nullable NSNumber *)gpsFirst
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs;
@property(nonatomic, copy) NSString * apiKey;
/// 0=GCJ02, 1=WGS84
@property(nonatomic, strong, nullable) NSNumber * coordinateType;
@property(nonatomic, strong, nullable) NSNumber * mockEnable;
/// 0/1/3/4 对应 GEO/NAME/ADMIN_AREA/POI
@property(nonatomic, strong, nullable) NSNumber * requestLevel;
/// Android: 10/11/12；iOS 忽略
@property(nonatomic, strong, nullable) NSNumber * locMode;
@property(nonatomic, strong, nullable) NSNumber * allowGps;
@property(nonatomic, strong, nullable) NSNumber * indoorLocationMode;
/// 首次是否等待卫星定位结果
@property(nonatomic, strong, nullable) NSNumber * gpsFirst;
/// 卫星定位优先时的超时时间 ms，最多 60000
@property(nonatomic, strong, nullable) NSNumber * gpsFirstTimeOutMs;
@end

/// 连续定位请求参数（与 TencentLocationRequest 对应）
@interface FLTContinuousLocationRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIntervalMs:(NSInteger )intervalMs
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    allowGps:(nullable NSNumber *)allowGps
    allowCache:(nullable NSNumber *)allowCache
    gpsFirst:(nullable NSNumber *)gpsFirst
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs
    backgroundLocation:(nullable NSNumber *)backgroundLocation;
/// 定位周期/回调周期，单位 ms。>0 时按周期回调；0 仅在有新结果时回调。建议 5000–10000
@property(nonatomic, assign) NSInteger  intervalMs;
/// 与 InitOptions 一致，不传则用 init 时的值
@property(nonatomic, strong, nullable) NSNumber * requestLevel;
@property(nonatomic, strong, nullable) NSNumber * locMode;
@property(nonatomic, strong, nullable) NSNumber * allowGps;
@property(nonatomic, strong, nullable) NSNumber * allowCache;
@property(nonatomic, strong, nullable) NSNumber * gpsFirst;
@property(nonatomic, strong, nullable) NSNumber * gpsFirstTimeOutMs;
/// 是否后台定位（Android 前台通知等）
@property(nonatomic, strong, nullable) NSNumber * backgroundLocation;
@end

/// 连续定位过程中可更新的参数（仅传需要修改的字段）
/// Android: 间隔可通过 changeCallbackInterval 修改；其它需重新 requestLocationUpdates
/// iOS: 可动态改 locationCallbackInterval、requestLevel 等属性
@interface FLTLocationRequestUpdate : NSObject
+ (instancetype)makeWithIntervalMs:(nullable NSNumber *)intervalMs
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs
    allowGps:(nullable NSNumber *)allowGps
    allowCache:(nullable NSNumber *)allowCache
    gpsFirst:(nullable NSNumber *)gpsFirst;
@property(nonatomic, strong, nullable) NSNumber * intervalMs;
@property(nonatomic, strong, nullable) NSNumber * requestLevel;
@property(nonatomic, strong, nullable) NSNumber * locMode;
@property(nonatomic, strong, nullable) NSNumber * gpsFirstTimeOutMs;
@property(nonatomic, strong, nullable) NSNumber * allowGps;
@property(nonatomic, strong, nullable) NSNumber * allowCache;
@property(nonatomic, strong, nullable) NSNumber * gpsFirst;
@end

/// Android 前台定位通知配置
@interface FLTAndroidNotificationOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSInteger )id
    channelId:(NSString *)channelId
    channelName:(NSString *)channelName
    channelDescription:(nullable NSString *)channelDescription
    notificationTitle:(NSString *)notificationTitle
    notificationText:(nullable NSString *)notificationText
    enableVibration:(nullable NSNumber *)enableVibration
    playSound:(nullable NSNumber *)playSound
    showWhen:(nullable NSNumber *)showWhen
    iconData:(nullable FLTNotificationIconData *)iconData;
@property(nonatomic, assign) NSInteger  id;
@property(nonatomic, copy) NSString * channelId;
@property(nonatomic, copy) NSString * channelName;
@property(nonatomic, copy, nullable) NSString * channelDescription;
@property(nonatomic, copy) NSString * notificationTitle;
@property(nonatomic, copy, nullable) NSString * notificationText;
@property(nonatomic, strong, nullable) NSNumber * enableVibration;
@property(nonatomic, strong, nullable) NSNumber * playSound;
@property(nonatomic, strong, nullable) NSNumber * showWhen;
@property(nonatomic, strong, nullable) FLTNotificationIconData * iconData;
@end

@interface FLTNotificationIconData : NSObject
+ (instancetype)makeWithBitmapPath:(nullable NSString *)bitmapPath
    resourceId:(nullable NSNumber *)resourceId;
@property(nonatomic, copy, nullable) NSString * bitmapPath;
@property(nonatomic, strong, nullable) NSNumber * resourceId;
@end

/// 定位结果（与 TencentLocation / TencentLBSLocation 对应）
@interface FLTLocationData : NSObject
+ (instancetype)makeWithCode:(nullable NSNumber *)code
    latitude:(nullable NSNumber *)latitude
    longitude:(nullable NSNumber *)longitude
    altitude:(nullable NSNumber *)altitude
    accuracy:(nullable NSNumber *)accuracy
    speed:(nullable NSNumber *)speed
    bearing:(nullable NSNumber *)bearing
    address:(nullable NSString *)address
    name:(nullable NSString *)name
    timeIso:(nullable NSString *)timeIso
    timeMs:(nullable NSNumber *)timeMs
    sourceProvider:(nullable NSString *)sourceProvider;
@property(nonatomic, strong, nullable) NSNumber * code;
@property(nonatomic, strong, nullable) NSNumber * latitude;
@property(nonatomic, strong, nullable) NSNumber * longitude;
@property(nonatomic, strong, nullable) NSNumber * altitude;
@property(nonatomic, strong, nullable) NSNumber * accuracy;
@property(nonatomic, strong, nullable) NSNumber * speed;
@property(nonatomic, strong, nullable) NSNumber * bearing;
@property(nonatomic, copy, nullable) NSString * address;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * timeIso;
@property(nonatomic, strong, nullable) NSNumber * timeMs;
@property(nonatomic, copy, nullable) NSString * sourceProvider;
@end

/// 状态回调（仅 Android onStatusUpdate）
@interface FLTLocationStatusData : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    status:(nullable NSNumber *)status;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * status;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FLTGetLocationPigeonCodec(void);

@protocol FLTTencentLBSHostApi
/// 对应 SDK 初始化（方法名避免 Swift 保留字 init）
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)configureOptions:(FLTInitOptions *)options error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserAgreePrivacyAgree:(BOOL)agree error:(FlutterError *_Nullable *_Nonnull)error;
- (void)requestLocationOnceWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)startLocationUpdatesRequest:(FLTContinuousLocationRequest *)request androidNotificationOptions:(nullable FLTAndroidNotificationOptions *)androidNotificationOptions error:(FlutterError *_Nullable *_Nonnull)error;
/// 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等）
- (void)updateLocationRequestUpdate:(nullable FLTLocationRequestUpdate *)update error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopLocationUpdatesWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLTTencentLBSHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTTencentLBSHostApi> *_Nullable api);

extern void SetUpFLTTencentLBSHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTTencentLBSHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface FLTTencentLBSFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onLocationLocation:(FLTLocationData *)location completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onErrorCode:(NSInteger)code message:(NSString *)message completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onStatusStatus:(nullable FLTLocationStatusData *)status completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
