// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 初始化参数（对应 init 时设置，与 SDK 文档一致）
///
/// Generated class from Pigeon that represents data sent in messages.
struct InitOptions {
  var apiKey: String
  /// 0=GCJ02, 1=WGS84
  var coordinateType: Int64? = nil
  var mockEnable: Bool? = nil
  /// 0/1/3/4 对应 GEO/NAME/ADMIN_AREA/POI
  var requestLevel: Int64? = nil
  /// Android: 10/11/12；iOS 忽略
  var locMode: Int64? = nil
  var allowGps: Bool? = nil
  var indoorLocationMode: Bool? = nil
  /// 首次是否等待卫星定位结果
  var gpsFirst: Bool? = nil
  /// 卫星定位优先时的超时时间 ms，最多 60000
  var gpsFirstTimeOutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitOptions? {
    let apiKey = pigeonVar_list[0] as! String
    let coordinateType: Int64? = nilOrValue(pigeonVar_list[1])
    let mockEnable: Bool? = nilOrValue(pigeonVar_list[2])
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[3])
    let locMode: Int64? = nilOrValue(pigeonVar_list[4])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[5])
    let indoorLocationMode: Bool? = nilOrValue(pigeonVar_list[6])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[7])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[8])

    return InitOptions(
      apiKey: apiKey,
      coordinateType: coordinateType,
      mockEnable: mockEnable,
      requestLevel: requestLevel,
      locMode: locMode,
      allowGps: allowGps,
      indoorLocationMode: indoorLocationMode,
      gpsFirst: gpsFirst,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    ]
  }
}

/// 连续定位请求参数（与 TencentLocationRequest 对应）
///
/// Generated class from Pigeon that represents data sent in messages.
struct ContinuousLocationRequest {
  /// 定位周期/回调周期，单位 ms。>0 时按周期回调；0 仅在有新结果时回调。建议 5000–10000
  var intervalMs: Int64
  /// 与 InitOptions 一致，不传则用 init 时的值
  var requestLevel: Int64? = nil
  var locMode: Int64? = nil
  var allowGps: Bool? = nil
  var allowCache: Bool? = nil
  var gpsFirst: Bool? = nil
  var gpsFirstTimeOutMs: Int64? = nil
  /// 是否后台定位（Android 前台通知等）
  var backgroundLocation: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContinuousLocationRequest? {
    let intervalMs = pigeonVar_list[0] as! Int64
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[1])
    let locMode: Int64? = nilOrValue(pigeonVar_list[2])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[3])
    let allowCache: Bool? = nilOrValue(pigeonVar_list[4])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[5])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[6])
    let backgroundLocation: Bool? = nilOrValue(pigeonVar_list[7])

    return ContinuousLocationRequest(
      intervalMs: intervalMs,
      requestLevel: requestLevel,
      locMode: locMode,
      allowGps: allowGps,
      allowCache: allowCache,
      gpsFirst: gpsFirst,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs,
      backgroundLocation: backgroundLocation
    )
  }
  func toList() -> [Any?] {
    return [
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    ]
  }
}

/// 连续定位过程中可更新的参数（仅传需要修改的字段）
/// Android: 间隔可通过 changeCallbackInterval 修改；其它需重新 requestLocationUpdates
/// iOS: 可动态改 locationCallbackInterval、requestLevel 等属性
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationRequestUpdate {
  var intervalMs: Int64? = nil
  var requestLevel: Int64? = nil
  var locMode: Int64? = nil
  var gpsFirstTimeOutMs: Int64? = nil
  var allowGps: Bool? = nil
  var allowCache: Bool? = nil
  var gpsFirst: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationRequestUpdate? {
    let intervalMs: Int64? = nilOrValue(pigeonVar_list[0])
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[1])
    let locMode: Int64? = nilOrValue(pigeonVar_list[2])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[3])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[4])
    let allowCache: Bool? = nilOrValue(pigeonVar_list[5])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[6])

    return LocationRequestUpdate(
      intervalMs: intervalMs,
      requestLevel: requestLevel,
      locMode: locMode,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs,
      allowGps: allowGps,
      allowCache: allowCache,
      gpsFirst: gpsFirst
    )
  }
  func toList() -> [Any?] {
    return [
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    ]
  }
}

/// Android 前台定位通知配置
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidNotificationOptions {
  var id: Int64
  var channelId: String
  var channelName: String
  var channelDescription: String? = nil
  var notificationTitle: String
  var notificationText: String? = nil
  var enableVibration: Bool? = nil
  var playSound: Bool? = nil
  var showWhen: Bool? = nil
  var iconData: NotificationIconData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidNotificationOptions? {
    let id = pigeonVar_list[0] as! Int64
    let channelId = pigeonVar_list[1] as! String
    let channelName = pigeonVar_list[2] as! String
    let channelDescription: String? = nilOrValue(pigeonVar_list[3])
    let notificationTitle = pigeonVar_list[4] as! String
    let notificationText: String? = nilOrValue(pigeonVar_list[5])
    let enableVibration: Bool? = nilOrValue(pigeonVar_list[6])
    let playSound: Bool? = nilOrValue(pigeonVar_list[7])
    let showWhen: Bool? = nilOrValue(pigeonVar_list[8])
    let iconData: NotificationIconData? = nilOrValue(pigeonVar_list[9])

    return AndroidNotificationOptions(
      id: id,
      channelId: channelId,
      channelName: channelName,
      channelDescription: channelDescription,
      notificationTitle: notificationTitle,
      notificationText: notificationText,
      enableVibration: enableVibration,
      playSound: playSound,
      showWhen: showWhen,
      iconData: iconData
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
      iconData,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotificationIconData {
  var bitmapPath: String? = nil
  var resourceId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationIconData? {
    let bitmapPath: String? = nilOrValue(pigeonVar_list[0])
    let resourceId: Int64? = nilOrValue(pigeonVar_list[1])

    return NotificationIconData(
      bitmapPath: bitmapPath,
      resourceId: resourceId
    )
  }
  func toList() -> [Any?] {
    return [
      bitmapPath,
      resourceId,
    ]
  }
}

/// 定位结果（与 TencentLocation / TencentLBSLocation 对应）
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationData {
  var code: Int64? = nil
  var latitude: Double? = nil
  var longitude: Double? = nil
  var altitude: Double? = nil
  var accuracy: Double? = nil
  var speed: Double? = nil
  var bearing: Double? = nil
  var address: String? = nil
  var name: String? = nil
  var timeIso: String? = nil
  var timeMs: Int64? = nil
  var sourceProvider: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationData? {
    let code: Int64? = nilOrValue(pigeonVar_list[0])
    let latitude: Double? = nilOrValue(pigeonVar_list[1])
    let longitude: Double? = nilOrValue(pigeonVar_list[2])
    let altitude: Double? = nilOrValue(pigeonVar_list[3])
    let accuracy: Double? = nilOrValue(pigeonVar_list[4])
    let speed: Double? = nilOrValue(pigeonVar_list[5])
    let bearing: Double? = nilOrValue(pigeonVar_list[6])
    let address: String? = nilOrValue(pigeonVar_list[7])
    let name: String? = nilOrValue(pigeonVar_list[8])
    let timeIso: String? = nilOrValue(pigeonVar_list[9])
    let timeMs: Int64? = nilOrValue(pigeonVar_list[10])
    let sourceProvider: String? = nilOrValue(pigeonVar_list[11])

    return LocationData(
      code: code,
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      accuracy: accuracy,
      speed: speed,
      bearing: bearing,
      address: address,
      name: name,
      timeIso: timeIso,
      timeMs: timeMs,
      sourceProvider: sourceProvider
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
    ]
  }
}

/// 状态回调（仅 Android onStatusUpdate）
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationStatusData {
  var name: String? = nil
  var status: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationStatusData? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let status: Int64? = nilOrValue(pigeonVar_list[1])

    return LocationStatusData(
      name: name,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      status,
    ]
  }
}

private class LocationPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return ContinuousLocationRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return LocationRequestUpdate.fromList(self.readValue() as! [Any?])
    case 132:
      return AndroidNotificationOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return NotificationIconData.fromList(self.readValue() as! [Any?])
    case 134:
      return LocationData.fromList(self.readValue() as! [Any?])
    case 135:
      return LocationStatusData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LocationPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ContinuousLocationRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LocationRequestUpdate {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidNotificationOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationIconData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? LocationData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? LocationStatusData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocationPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocationPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocationPigeonPigeonCodecWriter(data: data)
  }
}

class LocationPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LocationPigeonPigeonCodec(readerWriter: LocationPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TencentLBSHostApi {
  /// 对应 SDK 初始化（方法名避免 Swift 保留字 init）
  func configure(options: InitOptions) throws -> Bool
  func setUserAgreePrivacy(agree: Bool) throws
  func requestLocationOnce() throws
  func startLocationUpdates(request: ContinuousLocationRequest, androidNotificationOptions: AndroidNotificationOptions?) throws
  /// 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等）
  func updateLocationRequest(update: LocationRequestUpdate?) throws
  func stopLocationUpdates() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TencentLBSHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LocationPigeonPigeonCodec.shared }
  /// Sets up an instance of `TencentLBSHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TencentLBSHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 对应 SDK 初始化（方法名避免 Swift 保留字 init）
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! InitOptions
        do {
          let result = try api.configure(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let setUserAgreePrivacyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserAgreePrivacyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let agreeArg = args[0] as! Bool
        do {
          try api.setUserAgreePrivacy(agree: agreeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserAgreePrivacyChannel.setMessageHandler(nil)
    }
    let requestLocationOnceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestLocationOnceChannel.setMessageHandler { _, reply in
        do {
          try api.requestLocationOnce()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestLocationOnceChannel.setMessageHandler(nil)
    }
    let startLocationUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLocationUpdatesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ContinuousLocationRequest
        let androidNotificationOptionsArg: AndroidNotificationOptions? = nilOrValue(args[1])
        do {
          try api.startLocationUpdates(request: requestArg, androidNotificationOptions: androidNotificationOptionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startLocationUpdatesChannel.setMessageHandler(nil)
    }
    /// 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等）
    let updateLocationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateLocationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateArg: LocationRequestUpdate? = nilOrValue(args[0])
        do {
          try api.updateLocationRequest(update: updateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateLocationRequestChannel.setMessageHandler(nil)
    }
    let stopLocationUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLocationUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.stopLocationUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopLocationUpdatesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TencentLBSFlutterApiProtocol {
  func onLocation(location locationArg: LocationData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(code codeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStatus(status statusArg: LocationStatusData?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class TencentLBSFlutterApi: TencentLBSFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LocationPigeonPigeonCodec {
    return LocationPigeonPigeonCodec.shared
  }
  func onLocation(location locationArg: LocationData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([locationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(code codeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onStatus(status statusArg: LocationStatusData?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
