// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "LocationPigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FLTInitOptions ()
+ (FLTInitOptions *)fromList:(NSArray<id> *)list;
+ (nullable FLTInitOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTContinuousLocationRequest ()
+ (FLTContinuousLocationRequest *)fromList:(NSArray<id> *)list;
+ (nullable FLTContinuousLocationRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTLocationRequestUpdate ()
+ (FLTLocationRequestUpdate *)fromList:(NSArray<id> *)list;
+ (nullable FLTLocationRequestUpdate *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTAndroidNotificationOptions ()
+ (FLTAndroidNotificationOptions *)fromList:(NSArray<id> *)list;
+ (nullable FLTAndroidNotificationOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTNotificationIconData ()
+ (FLTNotificationIconData *)fromList:(NSArray<id> *)list;
+ (nullable FLTNotificationIconData *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTLocationData ()
+ (FLTLocationData *)fromList:(NSArray<id> *)list;
+ (nullable FLTLocationData *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTLocationStatusData ()
+ (FLTLocationStatusData *)fromList:(NSArray<id> *)list;
+ (nullable FLTLocationStatusData *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation FLTInitOptions
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    coordinateType:(nullable NSNumber *)coordinateType
    mockEnable:(nullable NSNumber *)mockEnable
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    allowGps:(nullable NSNumber *)allowGps
    indoorLocationMode:(nullable NSNumber *)indoorLocationMode
    gpsFirst:(nullable NSNumber *)gpsFirst
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs {
  FLTInitOptions* pigeonResult = [[FLTInitOptions alloc] init];
  pigeonResult.apiKey = apiKey;
  pigeonResult.coordinateType = coordinateType;
  pigeonResult.mockEnable = mockEnable;
  pigeonResult.requestLevel = requestLevel;
  pigeonResult.locMode = locMode;
  pigeonResult.allowGps = allowGps;
  pigeonResult.indoorLocationMode = indoorLocationMode;
  pigeonResult.gpsFirst = gpsFirst;
  pigeonResult.gpsFirstTimeOutMs = gpsFirstTimeOutMs;
  return pigeonResult;
}
+ (FLTInitOptions *)fromList:(NSArray<id> *)list {
  FLTInitOptions *pigeonResult = [[FLTInitOptions alloc] init];
  pigeonResult.apiKey = GetNullableObjectAtIndex(list, 0);
  pigeonResult.coordinateType = GetNullableObjectAtIndex(list, 1);
  pigeonResult.mockEnable = GetNullableObjectAtIndex(list, 2);
  pigeonResult.requestLevel = GetNullableObjectAtIndex(list, 3);
  pigeonResult.locMode = GetNullableObjectAtIndex(list, 4);
  pigeonResult.allowGps = GetNullableObjectAtIndex(list, 5);
  pigeonResult.indoorLocationMode = GetNullableObjectAtIndex(list, 6);
  pigeonResult.gpsFirst = GetNullableObjectAtIndex(list, 7);
  pigeonResult.gpsFirstTimeOutMs = GetNullableObjectAtIndex(list, 8);
  return pigeonResult;
}
+ (nullable FLTInitOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTInitOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.apiKey ?: [NSNull null],
    self.coordinateType ?: [NSNull null],
    self.mockEnable ?: [NSNull null],
    self.requestLevel ?: [NSNull null],
    self.locMode ?: [NSNull null],
    self.allowGps ?: [NSNull null],
    self.indoorLocationMode ?: [NSNull null],
    self.gpsFirst ?: [NSNull null],
    self.gpsFirstTimeOutMs ?: [NSNull null],
  ];
}
@end

@implementation FLTContinuousLocationRequest
+ (instancetype)makeWithIntervalMs:(NSInteger )intervalMs
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    allowGps:(nullable NSNumber *)allowGps
    allowCache:(nullable NSNumber *)allowCache
    gpsFirst:(nullable NSNumber *)gpsFirst
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs
    backgroundLocation:(nullable NSNumber *)backgroundLocation {
  FLTContinuousLocationRequest* pigeonResult = [[FLTContinuousLocationRequest alloc] init];
  pigeonResult.intervalMs = intervalMs;
  pigeonResult.requestLevel = requestLevel;
  pigeonResult.locMode = locMode;
  pigeonResult.allowGps = allowGps;
  pigeonResult.allowCache = allowCache;
  pigeonResult.gpsFirst = gpsFirst;
  pigeonResult.gpsFirstTimeOutMs = gpsFirstTimeOutMs;
  pigeonResult.backgroundLocation = backgroundLocation;
  return pigeonResult;
}
+ (FLTContinuousLocationRequest *)fromList:(NSArray<id> *)list {
  FLTContinuousLocationRequest *pigeonResult = [[FLTContinuousLocationRequest alloc] init];
  pigeonResult.intervalMs = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.requestLevel = GetNullableObjectAtIndex(list, 1);
  pigeonResult.locMode = GetNullableObjectAtIndex(list, 2);
  pigeonResult.allowGps = GetNullableObjectAtIndex(list, 3);
  pigeonResult.allowCache = GetNullableObjectAtIndex(list, 4);
  pigeonResult.gpsFirst = GetNullableObjectAtIndex(list, 5);
  pigeonResult.gpsFirstTimeOutMs = GetNullableObjectAtIndex(list, 6);
  pigeonResult.backgroundLocation = GetNullableObjectAtIndex(list, 7);
  return pigeonResult;
}
+ (nullable FLTContinuousLocationRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTContinuousLocationRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.intervalMs),
    self.requestLevel ?: [NSNull null],
    self.locMode ?: [NSNull null],
    self.allowGps ?: [NSNull null],
    self.allowCache ?: [NSNull null],
    self.gpsFirst ?: [NSNull null],
    self.gpsFirstTimeOutMs ?: [NSNull null],
    self.backgroundLocation ?: [NSNull null],
  ];
}
@end

@implementation FLTLocationRequestUpdate
+ (instancetype)makeWithIntervalMs:(nullable NSNumber *)intervalMs
    requestLevel:(nullable NSNumber *)requestLevel
    locMode:(nullable NSNumber *)locMode
    gpsFirstTimeOutMs:(nullable NSNumber *)gpsFirstTimeOutMs
    allowGps:(nullable NSNumber *)allowGps
    allowCache:(nullable NSNumber *)allowCache
    gpsFirst:(nullable NSNumber *)gpsFirst {
  FLTLocationRequestUpdate* pigeonResult = [[FLTLocationRequestUpdate alloc] init];
  pigeonResult.intervalMs = intervalMs;
  pigeonResult.requestLevel = requestLevel;
  pigeonResult.locMode = locMode;
  pigeonResult.gpsFirstTimeOutMs = gpsFirstTimeOutMs;
  pigeonResult.allowGps = allowGps;
  pigeonResult.allowCache = allowCache;
  pigeonResult.gpsFirst = gpsFirst;
  return pigeonResult;
}
+ (FLTLocationRequestUpdate *)fromList:(NSArray<id> *)list {
  FLTLocationRequestUpdate *pigeonResult = [[FLTLocationRequestUpdate alloc] init];
  pigeonResult.intervalMs = GetNullableObjectAtIndex(list, 0);
  pigeonResult.requestLevel = GetNullableObjectAtIndex(list, 1);
  pigeonResult.locMode = GetNullableObjectAtIndex(list, 2);
  pigeonResult.gpsFirstTimeOutMs = GetNullableObjectAtIndex(list, 3);
  pigeonResult.allowGps = GetNullableObjectAtIndex(list, 4);
  pigeonResult.allowCache = GetNullableObjectAtIndex(list, 5);
  pigeonResult.gpsFirst = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable FLTLocationRequestUpdate *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTLocationRequestUpdate fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.intervalMs ?: [NSNull null],
    self.requestLevel ?: [NSNull null],
    self.locMode ?: [NSNull null],
    self.gpsFirstTimeOutMs ?: [NSNull null],
    self.allowGps ?: [NSNull null],
    self.allowCache ?: [NSNull null],
    self.gpsFirst ?: [NSNull null],
  ];
}
@end

@implementation FLTAndroidNotificationOptions
+ (instancetype)makeWithId:(NSInteger )id
    channelId:(NSString *)channelId
    channelName:(NSString *)channelName
    channelDescription:(nullable NSString *)channelDescription
    notificationTitle:(NSString *)notificationTitle
    notificationText:(nullable NSString *)notificationText
    enableVibration:(nullable NSNumber *)enableVibration
    playSound:(nullable NSNumber *)playSound
    showWhen:(nullable NSNumber *)showWhen
    iconData:(nullable FLTNotificationIconData *)iconData {
  FLTAndroidNotificationOptions* pigeonResult = [[FLTAndroidNotificationOptions alloc] init];
  pigeonResult.id = id;
  pigeonResult.channelId = channelId;
  pigeonResult.channelName = channelName;
  pigeonResult.channelDescription = channelDescription;
  pigeonResult.notificationTitle = notificationTitle;
  pigeonResult.notificationText = notificationText;
  pigeonResult.enableVibration = enableVibration;
  pigeonResult.playSound = playSound;
  pigeonResult.showWhen = showWhen;
  pigeonResult.iconData = iconData;
  return pigeonResult;
}
+ (FLTAndroidNotificationOptions *)fromList:(NSArray<id> *)list {
  FLTAndroidNotificationOptions *pigeonResult = [[FLTAndroidNotificationOptions alloc] init];
  pigeonResult.id = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.channelId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.channelName = GetNullableObjectAtIndex(list, 2);
  pigeonResult.channelDescription = GetNullableObjectAtIndex(list, 3);
  pigeonResult.notificationTitle = GetNullableObjectAtIndex(list, 4);
  pigeonResult.notificationText = GetNullableObjectAtIndex(list, 5);
  pigeonResult.enableVibration = GetNullableObjectAtIndex(list, 6);
  pigeonResult.playSound = GetNullableObjectAtIndex(list, 7);
  pigeonResult.showWhen = GetNullableObjectAtIndex(list, 8);
  pigeonResult.iconData = GetNullableObjectAtIndex(list, 9);
  return pigeonResult;
}
+ (nullable FLTAndroidNotificationOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTAndroidNotificationOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.id),
    self.channelId ?: [NSNull null],
    self.channelName ?: [NSNull null],
    self.channelDescription ?: [NSNull null],
    self.notificationTitle ?: [NSNull null],
    self.notificationText ?: [NSNull null],
    self.enableVibration ?: [NSNull null],
    self.playSound ?: [NSNull null],
    self.showWhen ?: [NSNull null],
    self.iconData ?: [NSNull null],
  ];
}
@end

@implementation FLTNotificationIconData
+ (instancetype)makeWithBitmapPath:(nullable NSString *)bitmapPath
    resourceId:(nullable NSNumber *)resourceId {
  FLTNotificationIconData* pigeonResult = [[FLTNotificationIconData alloc] init];
  pigeonResult.bitmapPath = bitmapPath;
  pigeonResult.resourceId = resourceId;
  return pigeonResult;
}
+ (FLTNotificationIconData *)fromList:(NSArray<id> *)list {
  FLTNotificationIconData *pigeonResult = [[FLTNotificationIconData alloc] init];
  pigeonResult.bitmapPath = GetNullableObjectAtIndex(list, 0);
  pigeonResult.resourceId = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable FLTNotificationIconData *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTNotificationIconData fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.bitmapPath ?: [NSNull null],
    self.resourceId ?: [NSNull null],
  ];
}
@end

@implementation FLTLocationData
+ (instancetype)makeWithCode:(nullable NSNumber *)code
    latitude:(nullable NSNumber *)latitude
    longitude:(nullable NSNumber *)longitude
    altitude:(nullable NSNumber *)altitude
    accuracy:(nullable NSNumber *)accuracy
    speed:(nullable NSNumber *)speed
    bearing:(nullable NSNumber *)bearing
    address:(nullable NSString *)address
    name:(nullable NSString *)name
    timeIso:(nullable NSString *)timeIso
    timeMs:(nullable NSNumber *)timeMs
    sourceProvider:(nullable NSString *)sourceProvider {
  FLTLocationData* pigeonResult = [[FLTLocationData alloc] init];
  pigeonResult.code = code;
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  pigeonResult.altitude = altitude;
  pigeonResult.accuracy = accuracy;
  pigeonResult.speed = speed;
  pigeonResult.bearing = bearing;
  pigeonResult.address = address;
  pigeonResult.name = name;
  pigeonResult.timeIso = timeIso;
  pigeonResult.timeMs = timeMs;
  pigeonResult.sourceProvider = sourceProvider;
  return pigeonResult;
}
+ (FLTLocationData *)fromList:(NSArray<id> *)list {
  FLTLocationData *pigeonResult = [[FLTLocationData alloc] init];
  pigeonResult.code = GetNullableObjectAtIndex(list, 0);
  pigeonResult.latitude = GetNullableObjectAtIndex(list, 1);
  pigeonResult.longitude = GetNullableObjectAtIndex(list, 2);
  pigeonResult.altitude = GetNullableObjectAtIndex(list, 3);
  pigeonResult.accuracy = GetNullableObjectAtIndex(list, 4);
  pigeonResult.speed = GetNullableObjectAtIndex(list, 5);
  pigeonResult.bearing = GetNullableObjectAtIndex(list, 6);
  pigeonResult.address = GetNullableObjectAtIndex(list, 7);
  pigeonResult.name = GetNullableObjectAtIndex(list, 8);
  pigeonResult.timeIso = GetNullableObjectAtIndex(list, 9);
  pigeonResult.timeMs = GetNullableObjectAtIndex(list, 10);
  pigeonResult.sourceProvider = GetNullableObjectAtIndex(list, 11);
  return pigeonResult;
}
+ (nullable FLTLocationData *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTLocationData fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.code ?: [NSNull null],
    self.latitude ?: [NSNull null],
    self.longitude ?: [NSNull null],
    self.altitude ?: [NSNull null],
    self.accuracy ?: [NSNull null],
    self.speed ?: [NSNull null],
    self.bearing ?: [NSNull null],
    self.address ?: [NSNull null],
    self.name ?: [NSNull null],
    self.timeIso ?: [NSNull null],
    self.timeMs ?: [NSNull null],
    self.sourceProvider ?: [NSNull null],
  ];
}
@end

@implementation FLTLocationStatusData
+ (instancetype)makeWithName:(nullable NSString *)name
    status:(nullable NSNumber *)status {
  FLTLocationStatusData* pigeonResult = [[FLTLocationStatusData alloc] init];
  pigeonResult.name = name;
  pigeonResult.status = status;
  return pigeonResult;
}
+ (FLTLocationStatusData *)fromList:(NSArray<id> *)list {
  FLTLocationStatusData *pigeonResult = [[FLTLocationStatusData alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.status = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable FLTLocationStatusData *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTLocationStatusData fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.name ?: [NSNull null],
    self.status ?: [NSNull null],
  ];
}
@end

@interface FLTLocationPigeonPigeonCodecReader : FlutterStandardReader
@end
@implementation FLTLocationPigeonPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [FLTInitOptions fromList:[self readValue]];
    case 130: 
      return [FLTContinuousLocationRequest fromList:[self readValue]];
    case 131: 
      return [FLTLocationRequestUpdate fromList:[self readValue]];
    case 132: 
      return [FLTAndroidNotificationOptions fromList:[self readValue]];
    case 133: 
      return [FLTNotificationIconData fromList:[self readValue]];
    case 134: 
      return [FLTLocationData fromList:[self readValue]];
    case 135: 
      return [FLTLocationStatusData fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTLocationPigeonPigeonCodecWriter : FlutterStandardWriter
@end
@implementation FLTLocationPigeonPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTInitOptions class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTContinuousLocationRequest class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTLocationRequestUpdate class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTAndroidNotificationOptions class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTNotificationIconData class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTLocationData class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTLocationStatusData class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTLocationPigeonPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTLocationPigeonPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTLocationPigeonPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTLocationPigeonPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTGetLocationPigeonCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTLocationPigeonPigeonCodecReaderWriter *readerWriter = [[FLTLocationPigeonPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpFLTTencentLBSHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTTencentLBSHostApi> *api) {
  SetUpFLTTencentLBSHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpFLTTencentLBSHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTTencentLBSHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.init", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initOptions:error:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(initOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTInitOptions *arg_options = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api initOptions:arg_options error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setUserAgreePrivacyAgree:error:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(setUserAgreePrivacyAgree:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_agree = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setUserAgreePrivacyAgree:arg_agree error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestLocationOnceWithError:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(requestLocationOnceWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api requestLocationOnceWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startLocationUpdatesRequest:androidNotificationOptions:error:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(startLocationUpdatesRequest:androidNotificationOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTContinuousLocationRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FLTAndroidNotificationOptions *arg_androidNotificationOptions = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api startLocationUpdatesRequest:arg_request androidNotificationOptions:arg_androidNotificationOptions error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// 连续定位开启后可调用，更新部分参数（如超时时间、定位间隔等）
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updateLocationRequestUpdate:error:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(updateLocationRequestUpdate:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTLocationRequestUpdate *arg_update = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api updateLocationRequestUpdate:arg_update error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetLocationPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopLocationUpdatesWithError:)], @"FLTTencentLBSHostApi api (%@) doesn't respond to @selector(stopLocationUpdatesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopLocationUpdatesWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTTencentLBSFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation FLTTencentLBSFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onLocationLocation:(FLTLocationData *)arg_location completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:FLTGetLocationPigeonCodec()];
  [channel sendMessage:@[arg_location ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onErrorCode:(NSInteger)arg_code message:(NSString *)arg_message completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:FLTGetLocationPigeonCodec()];
  [channel sendMessage:@[@(arg_code), arg_message ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onStatusStatus:(nullable FLTLocationStatusData *)arg_status completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:FLTGetLocationPigeonCodec()];
  [channel sendMessage:@[arg_status ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

