// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 初始化参数。对应 Android TencentLocationManagerOptions + TencentLocationManager + TencentLocationRequest 的初始设置；iOS TencentLBSLocationManager 的 apiKey、coordinateType、requestLevel 等。
///
/// Generated class from Pigeon that represents data sent in messages.
struct InitOptions {
  /// 腾讯开放平台申请的 Key。Android: TencentLocationManagerOptions.setKey；iOS: apiKey。
  var apiKey: String
  /// 坐标系类型。0=GCJ02（火星坐标，大陆返回 GCJ02 大陆外返回 WGS84）；1=WGS84（地球坐标，均返回 WGS84）。Android: TencentLocationManager.coordinateType；iOS: TencentLBSLocationCoordinateType。
  var coordinateType: Int64? = nil
  /// 是否允许 Mock 定位。Android: TencentLocationManager.setMockEnable。
  var mockEnable: Bool? = nil
  /// 定位结果信息级别。不同 level 结果信息完整程度不同，信息越多消耗流量越多。Android: TencentLocationRequest.setRequestLevel。0=仅经纬度，1=经纬度+位置名称+地址，3=经纬度+行政区划+地址+名称，4=经纬度+行政区划+附近POI。
  var requestLevel: Int64? = nil
  /// 定位模式（仅 Android）。TencentLocationRequest.setLocMode。10=高精度(网络+卫星)，11=仅网络(不启GPS、省电、精度降低)，12=仅GPS(室外约3-10米，首次较慢耗电高，超时8s无GPS则返回网络)。iOS 无此参数，传参在 iOS 端忽略。
  var locMode: Int64? = nil
  /// 是否允许使用 GPS（仅 Android）。TencentLocationRequest.setAllowGPS，默认允许。允许时室外可提升精度约3-10米，首次较慢耗电较高。仅对高精度定位模式生效。
  var allowGps: Bool? = nil
  /// 是否启动室内定位（仅 Android）。TencentLocationRequest.setIndoorLocationMode。
  var indoorLocationMode: Bool? = nil
  /// 首次定位是否等待卫星定位结果（仅 Android）。TencentLocationRequest.setGpsFirst，默认 false。为 true 时首次定位会等待卫星结果，超时后返回网络定位结果。仅高精度模式生效。
  var gpsFirst: Bool? = nil
  /// 卫星定位优先时，等待卫星定位结果的超时时间（仅 Android）。TencentLocationRequest.setGpsFirstTimeOut，单位 ms，最多 60s。
  var gpsFirstTimeOutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitOptions? {
    let apiKey = pigeonVar_list[0] as! String
    let coordinateType: Int64? = nilOrValue(pigeonVar_list[1])
    let mockEnable: Bool? = nilOrValue(pigeonVar_list[2])
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[3])
    let locMode: Int64? = nilOrValue(pigeonVar_list[4])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[5])
    let indoorLocationMode: Bool? = nilOrValue(pigeonVar_list[6])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[7])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[8])

    return InitOptions(
      apiKey: apiKey,
      coordinateType: coordinateType,
      mockEnable: mockEnable,
      requestLevel: requestLevel,
      locMode: locMode,
      allowGps: allowGps,
      indoorLocationMode: indoorLocationMode,
      gpsFirst: gpsFirst,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      coordinateType,
      mockEnable,
      requestLevel,
      locMode,
      allowGps,
      indoorLocationMode,
      gpsFirst,
      gpsFirstTimeOutMs,
    ]
  }
}

/// 连续定位请求参数。对应 Android TencentLocationRequest；iOS 连续定位时的 interval、requestLevel 等。
///
/// Generated class from Pigeon that represents data sent in messages.
struct ContinuousLocationRequest {
  /// 定位周期（位置监听器回调周期），单位 ms。Android: TencentLocationRequest.setInterval。大于 0 时按周期定时回调；等于 0 时仅当有新的定位结果时回调。文档建议 5000-10000ms，不建议 1000ms 以下，且不得小于 1000ms。
  var intervalMs: Int64
  /// 定位结果信息级别，同 InitOptions.requestLevel。不传则使用 init 时的值。
  var requestLevel: Int64? = nil
  /// 定位模式（仅 Android），同 InitOptions.locMode。
  var locMode: Int64? = nil
  /// 是否允许使用 GPS（仅 Android），同 InitOptions.allowGps。
  var allowGps: Bool? = nil
  /// 是否允许使用缓存（仅 Android）。TencentLocationRequest.setAllowCache。允许时用户移动范围较小时可减少网络请求、节省电量和流量；长时间连续定位建议允许，单次定位建议不使用。
  var allowCache: Bool? = nil
  /// 首次是否等待卫星结果（仅 Android），同 InitOptions.gpsFirst。
  var gpsFirst: Bool? = nil
  /// 卫星优先超时时间 ms（仅 Android），同 InitOptions.gpsFirstTimeOutMs。
  var gpsFirstTimeOutMs: Int64? = nil
  /// 是否后台定位。为 true 时 Android 需配合前台通知（enableForegroundLocation）；iOS 需配置后台定位能力。
  var backgroundLocation: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContinuousLocationRequest? {
    let intervalMs = pigeonVar_list[0] as! Int64
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[1])
    let locMode: Int64? = nilOrValue(pigeonVar_list[2])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[3])
    let allowCache: Bool? = nilOrValue(pigeonVar_list[4])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[5])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[6])
    let backgroundLocation: Bool? = nilOrValue(pigeonVar_list[7])

    return ContinuousLocationRequest(
      intervalMs: intervalMs,
      requestLevel: requestLevel,
      locMode: locMode,
      allowGps: allowGps,
      allowCache: allowCache,
      gpsFirst: gpsFirst,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs,
      backgroundLocation: backgroundLocation
    )
  }
  func toList() -> [Any?] {
    return [
      intervalMs,
      requestLevel,
      locMode,
      allowGps,
      allowCache,
      gpsFirst,
      gpsFirstTimeOutMs,
      backgroundLocation,
    ]
  }
}

/// 连续定位过程中可更新的参数，仅传需要修改的字段。Android：间隔可通过 changeCallbackInterval 修改，其它需重新 requestLocationUpdates；iOS：可动态修改 locationCallbackInterval、requestLevel 等。
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationRequestUpdate {
  var intervalMs: Int64? = nil
  var requestLevel: Int64? = nil
  var locMode: Int64? = nil
  var gpsFirstTimeOutMs: Int64? = nil
  var allowGps: Bool? = nil
  var allowCache: Bool? = nil
  var gpsFirst: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationRequestUpdate? {
    let intervalMs: Int64? = nilOrValue(pigeonVar_list[0])
    let requestLevel: Int64? = nilOrValue(pigeonVar_list[1])
    let locMode: Int64? = nilOrValue(pigeonVar_list[2])
    let gpsFirstTimeOutMs: Int64? = nilOrValue(pigeonVar_list[3])
    let allowGps: Bool? = nilOrValue(pigeonVar_list[4])
    let allowCache: Bool? = nilOrValue(pigeonVar_list[5])
    let gpsFirst: Bool? = nilOrValue(pigeonVar_list[6])

    return LocationRequestUpdate(
      intervalMs: intervalMs,
      requestLevel: requestLevel,
      locMode: locMode,
      gpsFirstTimeOutMs: gpsFirstTimeOutMs,
      allowGps: allowGps,
      allowCache: allowCache,
      gpsFirst: gpsFirst
    )
  }
  func toList() -> [Any?] {
    return [
      intervalMs,
      requestLevel,
      locMode,
      gpsFirstTimeOutMs,
      allowGps,
      allowCache,
      gpsFirst,
    ]
  }
}

/// Android 后台定位时的前台通知配置。Android 后台定位需前台服务并显示通知，通过 TencentLocationManager.enableForegroundLocation(notifId, notification) 绑定；id 为通知 ID，channelId/channelName 为通知渠道，notificationTitle/notificationText 为通知标题与内容。
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidNotificationOptions {
  /// 前台定位通知 ID，用于 enableForegroundLocation(id, notification)。
  var id: Int64
  /// 通知渠道 ID（Android NotificationChannel）。
  var channelId: String
  /// 通知渠道名称。
  var channelName: String
  /// 通知渠道描述（可选）。
  var channelDescription: String? = nil
  /// 通知标题。
  var notificationTitle: String
  /// 通知内容（可选）。
  var notificationText: String? = nil
  /// 是否振动。
  var enableVibration: Bool? = nil
  /// 是否播放声音。
  var playSound: Bool? = nil
  /// 是否显示时间。
  var showWhen: Bool? = nil
  /// 通知图标（可选）。Android 侧用 bitmapPath 或 resourceId 解析为 drawable 资源。
  var iconData: NotificationIconData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidNotificationOptions? {
    let id = pigeonVar_list[0] as! Int64
    let channelId = pigeonVar_list[1] as! String
    let channelName = pigeonVar_list[2] as! String
    let channelDescription: String? = nilOrValue(pigeonVar_list[3])
    let notificationTitle = pigeonVar_list[4] as! String
    let notificationText: String? = nilOrValue(pigeonVar_list[5])
    let enableVibration: Bool? = nilOrValue(pigeonVar_list[6])
    let playSound: Bool? = nilOrValue(pigeonVar_list[7])
    let showWhen: Bool? = nilOrValue(pigeonVar_list[8])
    let iconData: NotificationIconData? = nilOrValue(pigeonVar_list[9])

    return AndroidNotificationOptions(
      id: id,
      channelId: channelId,
      channelName: channelName,
      channelDescription: channelDescription,
      notificationTitle: notificationTitle,
      notificationText: notificationText,
      enableVibration: enableVibration,
      playSound: playSound,
      showWhen: showWhen,
      iconData: iconData
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      channelId,
      channelName,
      channelDescription,
      notificationTitle,
      notificationText,
      enableVibration,
      playSound,
      showWhen,
      iconData,
    ]
  }
}

/// 通知图标数据，用于构建 Android 前台定位通知的小图标。bitmapPath 为本地路径；resourceId 为 Android drawable 资源 ID。
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationIconData {
  var bitmapPath: String? = nil
  var resourceId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationIconData? {
    let bitmapPath: String? = nilOrValue(pigeonVar_list[0])
    let resourceId: Int64? = nilOrValue(pigeonVar_list[1])

    return NotificationIconData(
      bitmapPath: bitmapPath,
      resourceId: resourceId
    )
  }
  func toList() -> [Any?] {
    return [
      bitmapPath,
      resourceId,
    ]
  }
}

/// 定位结果。对应 Android TencentLocation 接口、iOS TencentLBSLocation 返回字段。
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationData {
  /// 错误码。Android TencentLocation：0=ERROR_OK 定位成功，1=ERROR_NETWORK 网络问题，2=ERROR_BAD_JSON GPS/WiFi/基站错误，4=ERROR_WGS84 无法进行坐标转换，404=ERROR_UNKNOWN 未知原因。
  var code: Int64? = nil
  /// 纬度。TencentLocation.getLatitude。
  var latitude: Double? = nil
  /// 经度。TencentLocation.getLongitude。
  var longitude: Double? = nil
  /// 海拔，单位 m。TencentLocation.getAltitude，仅当位置来自 GPS 时可能有效。
  var altitude: Double? = nil
  /// 精度，单位 m（水平精度）。TencentLocation.getAccuracy / CLLocation.horizontalAccuracy。
  var accuracy: Double? = nil
  /// 水平精度，单位 m。与 accuracy 同源，语义明确。
  var horizontalAccuracy: Double? = nil
  /// 垂直精度（海拔精度），单位 m。仅 iOS CLLocation.verticalAccuracy 有值，Android 为 null。
  var verticalAccuracy: Double? = nil
  /// 移动速度，单位 m/s。TencentLocation.getSpeed，仅当位置来自 GPS 时可能有效。
  var speed: Double? = nil
  /// 方向/朝向，单位度（0～360）。TencentLocation.getBearing / CLLocation.course，仅当位置来自 GPS 时可能有效。
  var bearing: Double? = nil
  /// 位置地址。TencentLocation.getAddress，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。
  var address: String? = nil
  /// 位置名称。TencentLocation.getName，仅当 request level 为 NAME 或 ADMIN_AREA 时非 null。
  var name: String? = nil
  /// 时间 ISO 字符串（可选，非 SDK 必返字段）。
  var timeIso: String? = nil
  /// 当前位置生成时间，毫秒时间戳。TencentLocation.getTime。
  var timeMs: Int64? = nil
  /// 位置细分来源（原生原始值）。Android: TencentLocation.getSourceProvider()；iOS 可为 null，以 locationSource 为准。
  var sourceProvider: String? = nil
  /// 定位来源（双端统一）。-1=未知，0=GPS，1=网络，2=模拟，3=外设GPS，4=外设网络。见 LocationSource。
  var locationSource: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationData? {
    let code: Int64? = nilOrValue(pigeonVar_list[0])
    let latitude: Double? = nilOrValue(pigeonVar_list[1])
    let longitude: Double? = nilOrValue(pigeonVar_list[2])
    let altitude: Double? = nilOrValue(pigeonVar_list[3])
    let accuracy: Double? = nilOrValue(pigeonVar_list[4])
    let horizontalAccuracy: Double? = nilOrValue(pigeonVar_list[5])
    let verticalAccuracy: Double? = nilOrValue(pigeonVar_list[6])
    let speed: Double? = nilOrValue(pigeonVar_list[7])
    let bearing: Double? = nilOrValue(pigeonVar_list[8])
    let address: String? = nilOrValue(pigeonVar_list[9])
    let name: String? = nilOrValue(pigeonVar_list[10])
    let timeIso: String? = nilOrValue(pigeonVar_list[11])
    let timeMs: Int64? = nilOrValue(pigeonVar_list[12])
    let sourceProvider: String? = nilOrValue(pigeonVar_list[13])
    let locationSource: Int64? = nilOrValue(pigeonVar_list[14])

    return LocationData(
      code: code,
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      accuracy: accuracy,
      horizontalAccuracy: horizontalAccuracy,
      verticalAccuracy: verticalAccuracy,
      speed: speed,
      bearing: bearing,
      address: address,
      name: name,
      timeIso: timeIso,
      timeMs: timeMs,
      sourceProvider: sourceProvider,
      locationSource: locationSource
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      latitude,
      longitude,
      altitude,
      accuracy,
      horizontalAccuracy,
      verticalAccuracy,
      speed,
      bearing,
      address,
      name,
      timeIso,
      timeMs,
      sourceProvider,
      locationSource,
    ]
  }
}

/// 状态回调数据（仅 Android）。对应 TencentLocationListener.onStatusUpdate(name, status, desc)。使用 status 前请先按 name 区分设备。name 为设备名如 "GPS"、"WIFI"、"CELL"；status 为状态码，参见 SDK 状态码对照表。
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocationStatusData {
  var name: String? = nil
  var status: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationStatusData? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let status: Int64? = nilOrValue(pigeonVar_list[1])

    return LocationStatusData(
      name: name,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      status,
    ]
  }
}

private class LocationPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return ContinuousLocationRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return LocationRequestUpdate.fromList(self.readValue() as! [Any?])
    case 132:
      return AndroidNotificationOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return NotificationIconData.fromList(self.readValue() as! [Any?])
    case 134:
      return LocationData.fromList(self.readValue() as! [Any?])
    case 135:
      return LocationStatusData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LocationPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ContinuousLocationRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LocationRequestUpdate {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidNotificationOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationIconData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? LocationData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? LocationStatusData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocationPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocationPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocationPigeonPigeonCodecWriter(data: data)
  }
}

class LocationPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LocationPigeonPigeonCodec(readerWriter: LocationPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TencentLBSHostApi {
  /// SDK 初始化（方法名避免 Swift 保留字 init）。Android: TencentLocationManagerOptions.setKey + TencentLocationManager 实例及 Request 配置；iOS: TencentLBSLocationManager 配置。
  func configure(options: InitOptions) throws -> Bool
  /// 设置用户是否同意隐私政策，调用其他接口前必须调用。对应 SDK setUserAgreePrivacy。
  func setUserAgreePrivacy(agree: Bool) throws
  /// 单次定位。Android: requestSingleFreshLocation；iOS: requestLocation。
  func requestLocationOnce() throws
  /// 发起连续定位。Android: requestLocationUpdates；iOS: startUpdatingLocation。androidNotificationOptions 仅 Android 后台定位时用于构建前台通知。
  func startLocationUpdates(request: ContinuousLocationRequest, androidNotificationOptions: AndroidNotificationOptions?) throws
  /// 连续定位开启后可调用，更新部分参数（如定位间隔、requestLevel 等）。Android 间隔可通过 changeCallbackInterval 修改。
  func updateLocationRequest(update: LocationRequestUpdate?) throws
  /// 停止连续定位。Android: removeUpdates；iOS: stopUpdatingLocation。
  func stopLocationUpdates() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TencentLBSHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LocationPigeonPigeonCodec.shared }
  /// Sets up an instance of `TencentLBSHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TencentLBSHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// SDK 初始化（方法名避免 Swift 保留字 init）。Android: TencentLocationManagerOptions.setKey + TencentLocationManager 实例及 Request 配置；iOS: TencentLBSLocationManager 配置。
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! InitOptions
        do {
          let result = try api.configure(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// 设置用户是否同意隐私政策，调用其他接口前必须调用。对应 SDK setUserAgreePrivacy。
    let setUserAgreePrivacyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.setUserAgreePrivacy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserAgreePrivacyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let agreeArg = args[0] as! Bool
        do {
          try api.setUserAgreePrivacy(agree: agreeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserAgreePrivacyChannel.setMessageHandler(nil)
    }
    /// 单次定位。Android: requestSingleFreshLocation；iOS: requestLocation。
    let requestLocationOnceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.requestLocationOnce\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestLocationOnceChannel.setMessageHandler { _, reply in
        do {
          try api.requestLocationOnce()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestLocationOnceChannel.setMessageHandler(nil)
    }
    /// 发起连续定位。Android: requestLocationUpdates；iOS: startUpdatingLocation。androidNotificationOptions 仅 Android 后台定位时用于构建前台通知。
    let startLocationUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.startLocationUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLocationUpdatesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ContinuousLocationRequest
        let androidNotificationOptionsArg: AndroidNotificationOptions? = nilOrValue(args[1])
        do {
          try api.startLocationUpdates(request: requestArg, androidNotificationOptions: androidNotificationOptionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startLocationUpdatesChannel.setMessageHandler(nil)
    }
    /// 连续定位开启后可调用，更新部分参数（如定位间隔、requestLevel 等）。Android 间隔可通过 changeCallbackInterval 修改。
    let updateLocationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.updateLocationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateLocationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateArg: LocationRequestUpdate? = nilOrValue(args[0])
        do {
          try api.updateLocationRequest(update: updateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateLocationRequestChannel.setMessageHandler(nil)
    }
    /// 停止连续定位。Android: removeUpdates；iOS: stopUpdatingLocation。
    let stopLocationUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSHostApi.stopLocationUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLocationUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.stopLocationUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopLocationUpdatesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TencentLBSFlutterApiProtocol {
  func onLocation(location locationArg: LocationData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(code codeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStatus(status statusArg: LocationStatusData?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class TencentLBSFlutterApi: TencentLBSFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LocationPigeonPigeonCodec {
    return LocationPigeonPigeonCodec.shared
  }
  func onLocation(location locationArg: LocationData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onLocation\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([locationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(code codeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onStatus(status statusArg: LocationStatusData?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_tencent_lbs_plugin.TencentLBSFlutterApi.onStatus\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
